### ISSUE TITLE
Open H5 file in readonly mode

### ISSUE THREAD

**Issue by soomy** [istb-mia/miapy#7]
Use the mode='r' parameter of h5py.File(self.file_path, libver='latest') in miapy/data/extraction/reader.py to open the h5 in readonly mode.
Reason: Sometimes during a debugging session the file seems to be kept blocked and ill have to reset its flags manually (h5clear -s <file>).
As we are not writing to the file, readonly would make sense anyway...

**Comment by fabianbalsiger** [comment]
@alainjungo Do you see any problems with this?

**Comment by alainjungo** [comment]
@fabianbalsiger Not really. Since it is called reader we should only use it for reading purposes.

@soomy  I think you already fixed this in your clone. Can you directly provide a pull request?

**Comment by soomy** [comment]
Done!
